#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  setup-ca-certs-image
  namespace: cert-injection-webhook
data:
  image: #@ data.values.setup_ca_certs_image or assert.fail("missing setup_ca_certs_image")
---
apiVersion: v1
kind: Secret
metadata:
  name:  cert-injection-webhook-tls
  namespace: cert-injection-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-injection-webhook
  namespace: cert-injection-webhook
  labels:
    app: cert-injection-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-injection-webhook
  template:
    metadata:
      labels:
        app: cert-injection-webhook
    spec:
      serviceAccountName: cert-injection-webhook-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: server
          image: #@ data.values.webhook_image or assert.fail("missing webhook_image")
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL
          imagePullPolicy: Always
          volumeMounts:
            - name: webhook-ca-cert
              mountPath: /run/config_maps/ca_cert
              readOnly: true
            - name: http-proxy
              mountPath: /run/config_maps/http_proxy
              readOnly: true
            - name: https-proxy
              mountPath: /run/config_maps/https_proxy
              readOnly: true
            - name: no-proxy
              mountPath: /run/config_maps/no_proxy
              readOnly: true
          ports:
            - containerPort: 8443
              name: webhook-port
          env:
            - name: SETUP_CA_CERTS_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: setup-ca-certs-image
                  key: image
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: webhook-ca-cert
          configMap:
            name: ca-cert
        - name: http-proxy
          configMap:
            name: http-proxy
        - name: https-proxy
          configMap:
            name: https-proxy
        - name: no-proxy
          configMap:
            name: no-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: cert-injection-webhook
  namespace: cert-injection-webhook
spec:
  selector:
    app: cert-injection-webhook
  ports:
    - port: 443
      targetPort: webhook-port
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaults.webhook.cert-injection.tanzu.vmware.com
webhooks:
  - name: defaults.webhook.cert-injection.tanzu.vmware.com
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cert-injection-webhook
        namespace: cert-injection-webhook
        path: /certinjectionwebhook
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-injection-webhook-sa
  namespace: cert-injection-webhook
